steps:
  - name: Probo site setup
    plugin: Drupal
    makeFile: build-vih.make
    profileName: vih_dk
    runInstall: true
    revertFeatures: true
  - name: Enabling deploy module
    command: 'drush --root="/var/www/html" en vih_deploy -y'
  - name: Enable stage_file_proxy
    command: 'drush --root="/var/www/html" en stage_file_proxy -y'
    command: 'drush variable-set stage_file_proxy_origin "http://vih.dk"'
