core = 7.x
api = 2

;;;;;;;;;
; Custom modules
;;;;;;;;;

projects[vih_ad_push][type] = "module"
projects[vih_ad_push][subdir] = "vih"
projects[vih_ad_push][download][type] = "git"
projects[vih_ad_push][download][url] = "https://github.com/vih/vih_ad_push.git"
projects[vih_ad_push][download][branch] = "7.x-1.x"
projects[vih_ad_push][download][revision] = "dd118d517dab5d1c3465f6f6260ce0eb841826cf"

projects[vih_calendar][type] = "module"
projects[vih_calendar][subdir] = "vih"
projects[vih_calendar][download][type] = "git"
projects[vih_calendar][download][url] = "https://github.com/vih/vih_calendar.git"
projects[vih_calendar][download][branch] = "7.x-1.x"
projects[vih_calendar][download][revision] = "ec298fbcd48b5f3079153901543d8657a36bb22c"

projects[vih_core][type] = "module"
projects[vih_core][subdir] = "vih"
projects[vih_core][download][type] = "git"
projects[vih_core][download][url] = "https://github.com/vih/vih_core.git"
projects[vih_core][download][branch] = "7.x-1.x"
projects[vih_core][download][revision] = "fea29232758e1756562220d951edab19558ef749"

projects[vih_dashboard][type] = "module"
projects[vih_dashboard][subdir] = "vih"
projects[vih_dashboard][download][type] = "git"
projects[vih_dashboard][download][url] = "https://github.com/vih/vih_dashboard.git"
projects[vih_dashboard][download][branch] = "7.x-1.x"
projects[vih_dashboard][download][revision] = "b01b3f8265b4e1182258a337d3fea867792d6074"

projects[vih_deploy][type] = "module"
projects[vih_deploy][subdir] = "vih"
projects[vih_deploy][download][type] = "git"
projects[vih_deploy][download][url] = "https://github.com/vih/vih_deploy.git"
projects[vih_deploy][download][branch] = "7.x-1.x"
projects[vih_deploy][download][revision] = "500f8342193c192a9adc1791485f8c2e3adaf1d3"

projects[vih_employees][type] = "module"
projects[vih_employees][subdir] = "vih"
projects[vih_employees][download][type] = "git"
projects[vih_employees][download][url] = "https://github.com/vih/vih_employees.git"
projects[vih_employees][download][branch] = "7.x-1.x"
projects[vih_employees][download][revision] = "be23166"

projects[vih_facilities][type] = "module"
projects[vih_facilities][subdir] = "vih"
projects[vih_facilities][download][type] = "git"
projects[vih_facilities][download][url] = "https://github.com/vih/vih_facilities.git"
projects[vih_facilities][download][branch] = "7.x-1.x"
projects[vih_facilities][download][revision] = "60cd026"

projects[vih_golf_courses][type] = "module"
projects[vih_golf_courses][subdir] = "vih"
projects[vih_golf_courses][download][type] = "git"
projects[vih_golf_courses][download][url] = "https://github.com/vih/vih_golf_courses.git"
projects[vih_golf_courses][download][branch] = "7.x-1.x"
projects[vih_golf_courses][download][revision] = "ac2c97b"

projects[vih_help][type] = "module"
projects[vih_help][subdir] = "vih"
projects[vih_help][download][type] = "git"
projects[vih_help][download][url] = "https://github.com/vih/vih_help.git"
projects[vih_help][download][branch] = "7.x-1.x"
projects[vih_help][download][revision] = "ca66fe9e269ee90749ffbd607fb44c1a9836848a"

projects[vih_images][type] = "module"
projects[vih_images][subdir] = "vih"
projects[vih_images][download][type] = "git"
projects[vih_images][download][url] = "https://github.com/vih/vih_images.git"
projects[vih_images][download][branch] = "7.x-1.x"
projects[vih_images][download][revision] = "7eefb34a13a69dbf1ef3d57478c27b36a9f1b3e4"

projects[vih_kalendersiden][type] = "module"
projects[vih_kalendersiden][subdir] = "vih"
projects[vih_kalendersiden][download][type] = "git"
projects[vih_kalendersiden][download][url] = "https://github.com/vih/vih_kalendersiden.git"
projects[vih_kalendersiden][download][branch] = "7.x-1.x"
projects[vih_kalendersiden][download][revision] = "993012627508a2e83d4e5181068bae82d244c4a4"

projects[vih_lectures][type] = "module"
projects[vih_lectures][subdir] = "vih"
projects[vih_lectures][download][type] = "git"
projects[vih_lectures][download][url] = "https://github.com/vih/vih_lectures.git"
projects[vih_lectures][download][branch] = "7.x-1.x"
projects[vih_lectures][download][revision] = "506d480"

projects[vih_lectures_pdf][type] = "module"
projects[vih_lectures_pdf][subdir] = "vih"
projects[vih_lectures_pdf][download][type] = "git"
projects[vih_lectures_pdf][download][url] = "https://github.com/vih/vih_lectures_pdf.git"
projects[vih_lectures_pdf][download][branch] = "7.x-1.x"
projects[vih_lectures_pdf][download][revision] = "12007fa59f74fb9120495dcba76168ccff852cf4"

projects[vih_long_course][type] = "module"
projects[vih_long_course][subdir] = "vih"
projects[vih_long_course][download][type] = "git"
projects[vih_long_course][download][url] = "https://github.com/vih/vih_long_course.git"
projects[vih_long_course][download][branch] = "7.x-1.x"
projects[vih_long_course][download][revision] = "7e824f40b26c445115c711fd3d5cf4f3926fc5d8"

projects[vih_participant_quotes][type] = "module"
projects[vih_participant_quotes][subdir] = "vih"
projects[vih_participant_quotes][download][type] = "git"
projects[vih_participant_quotes][download][url] = "https://github.com/vih/vih_participant_quotes.git"
projects[vih_participant_quotes][download][branch] = "7.x-1.x"
projects[vih_participant_quotes][download][revision] = "ffde31a335be32d95e8f9465edaaef5a121f873c"

projects[vih_short_course][type] = "module"
projects[vih_short_course][subdir] = "vih"
projects[vih_short_course][download][type] = "git"
projects[vih_short_course][download][url] = "https://github.com/vih/vih_short_course.git"
projects[vih_short_course][download][branch] = "7.x-1.x"
projects[vih_short_course][download][revision] = "a4733ea"

projects[vih_short_course_commerce][type] = "module"
projects[vih_short_course_commerce][subdir] = "vih"
projects[vih_short_course_commerce][download][type] = "git"
projects[vih_short_course_commerce][download][url] = "https://github.com/vih/vih_short_course_commerce.git"
projects[vih_short_course_commerce][download][branch] = "7.x-1.x"
projects[vih_short_course_commerce][download][revision] = "74fe2399d1f69b2e91afbcdec290ce143ab70cea"

projects[vih_short_course_kayak][type] = "module"
projects[vih_short_course_kayak][subdir] = "vih"
projects[vih_short_course_kayak][download][type] = "git"
projects[vih_short_course_kayak][download][url] = "https://github.com/vih/vih_short_course_kayak.git"
projects[vih_short_course_kayak][download][branch] = "7.x-1.x"
projects[vih_short_course_kayak][download][revision] = "6770f7c3d8f94f93d9c9aa2d24adcca0e17101e1"

projects[vih_stories][type] = "module"
projects[vih_stories][subdir] = "vih"
projects[vih_stories][download][type] = "git"
projects[vih_stories][download][url] = "https://github.com/vih/vih_stories.git"
projects[vih_stories][download][branch] = "7.x-1.x"
projects[vih_stories][download][revision] = "faf237351da08d2a9172bedf2337495e95570e5c"

projects[vih_student_quotes][type] = "module"
projects[vih_student_quotes][subdir] = "vih"
projects[vih_student_quotes][download][type] = "git"
projects[vih_student_quotes][download][url] = "https://github.com/vih/vih_student_quotes.git"
projects[vih_student_quotes][download][branch] = "7.x-1.x"
projects[vih_student_quotes][download][revision] = "d5e8a743b8a9b76f146615ea22d22e011d8360af"

projects[vih_subjects][type] = "module"
projects[vih_subjects][subdir] = "vih"
projects[vih_subjects][download][type] = "git"
projects[vih_subjects][download][url] = "https://github.com/vih/vih_subjects.git"
projects[vih_subjects][download][branch] = "7.x-1.x"
projects[vih_subjects][download][revision] = "4f0f322a5a85b0f09152e96e0da0ab0c561f165c"

projects[vih_viggo][type] = "module"
projects[vih_viggo][subdir] = "vih"
projects[vih_viggo][download][type] = "git"
projects[vih_viggo][download][url] = "https://github.com/vih/vih_viggo.git"
projects[vih_viggo][download][branch] = "7.x-1.x"
projects[vih_viggo][download][revision] = "f18c049f0605b2678a2e0ae128b3b34c2be5ac57"

;;;;;;;;;
; Themes
;;;;;;;;;

projects[sport][type] = "theme"
projects[sport][download][type] = "git"
projects[sport][download][url] = "https://github.com/vih/sport-theme.git"
projects[sport][download][branch] = "7.x-1.x"
projects[sport][download][revision] = "ac5a12c"
